### ISSUE TITLE
Icon in button

### ISSUE THREAD

**Issue by timmy78** [newerton/yii2-jcrop#4]
Hi

Thank you for your widget.

Is there a way to not encode HTML in buttons ?
For example I want this in my configuration : 

```
'buttons' => array(
        'start' => array(
            'label' => '<i class="fa fa-crop"></i> Crop',
...
```

Thank you !

**Comment by newerton** [comment]
@timmy78 
I made a code change, not now encode the HTML.

Thank you!

**Comment by newerton** [comment]
@timmy78 
I made a small wiki:
https://github.com/newerton/yii2-jcrop/wiki/Configuration
